# Snowflake Container Services configuration for cyphr AI Extension
version: 1.0

spec:
  containers:
    - name: cyphr-ai-extension
      image: cyphr-ai-extension:latest
      env:
        - name: SNOWFLAKE_ACCOUNT
          value: ${SNOWFLAKE_ACCOUNT}
        - name: SNOWFLAKE_USER
          value: ${SNOWFLAKE_USER}
        - name: SNOWFLAKE_PASSWORD
          value: ${SNOWFLAKE_PASSWORD}
        - name: SNOWFLAKE_WAREHOUSE
          value: ${SNOWFLAKE_WAREHOUSE}
        - name: SNOWFLAKE_DATABASE
          value: ${SNOWFLAKE_DATABASE}
        - name: SNOWFLAKE_SCHEMA
          value: ${SNOWFLAKE_SCHEMA}
        - name: SNOWFLAKE_ROLE
          value: ${SNOWFLAKE_ROLE}
      ports:
        - name: http
          port: 8000
      resources:
        cpu: 1
        memory: 2Gi
  endpoint:
    - name: cyphr-ai-extension-api
      port: 8000
      public: true
  compute:
    instanceSize: X-Small  # 1 CPU, 2GB memory