version: '3.8'

services:
  snowpark:
    build:
      context: .
      dockerfile: Dockerfile.snowpark
    ports:
      - "8080:80"  # Map container port 80 to host port 8080
    environment:
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT:-}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER:-}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD:-}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE:-}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE:-}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA:-}
      - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE:-}
    volumes:
      - ./database:/app/database
    restart: unless-stopped